version: '3'

services:
  app:
    build: app/devel
    logging:
      driver: 'json-file'
      options:
        max-size: 100k
        max-file: '1'
    depends_on:
      - redis
    networks:
      frontend:
        aliases:
          - adf.docker
      default:
    volumes:
      - ./app/src:/app
      - app-views:/app/storage/views
      - app-logs:/app/storage/logs
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: /app/setup.sh
    command: "supervisord --configuration /etc/supervisord.conf"
  
  postgres:
    image: postgres:11-alpine
    logging:
      driver: 'json-file'
      options:
        max-size: 100k
        max-file: '1'
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  redis:
    image: redis:4-alpine
    logging:
      driver: 'json-file'
      options:
        max-size: 100k
        max-file: '1'
    volumes:
      - redis-data:/data

networks:
  frontend:
    external: true

volumes:
  app-logs:
  app-views:
  pg-data:
  redis-data:
