version: '3'

services:
  app:
    build: app/devel
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app/src:/app
      - app-views:/app/storage/views
      - app-logs:/app/storage/logs
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  
  postgres:
    image: postgres:11-alpine
    logging:
      driver: 'json-file'
      options:
        max-size: 100k
        max-file: '1'
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  redis:
    image: redis:4-alpine
    logging:
      driver: 'json-file'
      options:
        max-size: 100k
        max-file: '1'
    volumes:
      - redis-data:/data

volumes:
  app-logs:
  app-views:
  pg-data:
  redis-data:
